import React from "react";

export const metadata = {
  title: "Program",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return <div className=" mx-auto mt-10">{children}</div>;
};

export default layout;
