import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Donasi Aps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased tracking-tight`}
      >
        <Navbar />
        <main className="mt-16 w-full max-w-[1800px] mx-auto py-2">
          {children}
        </main>
      </body>
    </html>
  );
}
